### PR TITLE
Bug fixed issue #25,#44

### PR DESCRIPTION
**Pull request by oOhoraOo**
2 bug fixed. 
- Fixed deletePrivateData.
- Fixed the query scope of getStateByRange, getPrivateDataByRange.

### CODE REVIEW

**Comment by sneljo1** [comment]
Nice. Could you also add some specific test cases for this?

**Comment by oOhoraOo** [comment]
Thank you for checking. OK, please wait for some days.

**Comment by oOhoraOo** [comment]
hi.
I've  committed some testcases for the Fixes #25 , #44 .
Please confirm.

**Comment by sneljo1** [comment]
Thanks for your contribution.

**Pull request merged**
